apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--article-store
  labels:
    {{- include "publisher.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: NodePort
  ports:
    - targetPort: http
      port: 80
      protocol: TCP
  selector:
    {{- include "publisher.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: article-store
