apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--article-page
  labels:
    {{- include "publisher.labels" . | nindent 4 }}
    app.kubernetes.io/component: article-page
spec:
  selector:
    matchLabels:
      {{- include "publisher.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: article-page
  template:
    metadata:
      labels:
        {{- include "publisher.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: article-page
    spec:
      containers:
        - name: app
          image: "{{ .Values.images.articlePage.repository }}:latest"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
